const mongoose = require('mongoose');
const Schema = new mongoose.Schema({
    title:{
        type:String,
        required:true,
    },
    qty:{
        type:Number,
        required:true,
    },
    price:{
        type:Number,
        required:true,
    },
    category:{
        type:String,
        required:true,
    },
    desc:{
        type:String,
        required:true,
    },
    shortDesc:{
        type:String,
        required:true,
        maxlength:97,
    },
    slider:{
        type:Array,
        default:[],
    },
    image:{
        type:String,
        required:true,
    },
    category:{
        type:String,
        required:true,
    },
    recently:{
        type:Boolean,
        default:true
    },
    stars:{
        type:Array,
        default:[],
    },
    discount:{
        type:Boolean,
        default:false 
    },
    discountPrice:{
        type:Number,
        default:0,
    },
    discountPercentage:{
        type:Number,
        default:0
    },
    date:{
        type:String,
        required:true,
    },
    active:{
        type:Boolean,
        default:true
    },
    addedScore:{
        type:Number,
        required:true
    },
    discountScore:{
        type:Object,
        required:true
    },
    discountScoreActive:{
        type:Boolean,
        default:true
    },
    userQty:{
        type:Number,
        default:0,
    },
    checkBuyWithPoints:{
        type:Boolean,
        default:false,
    },
    path:{
        type:String,
        required:true
    },
    buyScore:{
        type:Number,
        default:0
    }
});
const Product = mongoose.model('products' , Schema);
module.exports = Product;