export const types = {
    //PRODUCTS TYPES
    PRODUCTS_LOADING:'PRODUCTS_LOADING',
    PRODUCTS_LODAED:'PRODUCTS_LODAED',

    PRODUCT_LOADING:'PRODUCT_LOADING',
    PRODUCT_LOADED:'PRODUCT_LODAED',
    SEARCH_START:'SEARCH_START',
    SEARCH_END:'SEARCH_END',
    //CATEGORIES TYPES
    GET_CATEGORIES:'GET_CATEGORYS',
    CATEGORIES_LOADING:'CATEGORIES_LOADING',
    CATEGORIES_LOADED:'CATEGORIES_LOADED',

    //USER TYPES
    USER_LODAED:'USER_LODAED',
    USER_LOADING:'USER_LOADING',
    USER_ERR:'USER_ERR',
};